# Generated by Django 2.1.8 on 2019-04-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20190405_1524'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='song',
            name='playlist_so_video_i_6be463_idx',
        ),
        migrations.AlterField(
            model_name='song',
            name='video_id',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
