# Generated by Django 2.1.8 on 2019-04-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20190407_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='video_id',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['video_id'], name='playlist_so_video_i_6be463_idx'),
        ),
    ]
