# Generated by Django 2.1.8 on 2019-04-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_auto_20190407_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
