# Generated by Django 2.1.8 on 2019-04-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_auto_20190407_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='playlist',
        ),
        migrations.AddField(
            model_name='song',
            name='playlists',
            field=models.ManyToManyField(related_name='songs', to='playlist.Playlist'),
        ),
    ]
