# Generated by Django 2.1.8 on 2019-04-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0006_auto_20190411_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='playlists',
            field=models.ManyToManyField(blank=True, null=True, related_name='songs', to='playlist.Playlist'),
        ),
    ]
