# Generated by Django 2.1.8 on 2019-04-11 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0008_auto_20190411_1237'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='song',
            name='playlist_so_video_i_6be463_idx',
        ),
        migrations.RemoveField(
            model_name='song',
            name='playlists',
        ),
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='playlist.Playlist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='video_id',
            field=models.CharField(max_length=32),
        ),
    ]
