# Generated by Django 2.1.8 on 2019-04-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0009_auto_20190411_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
